export const posts = [
    {
        id: 1,
        title: "5 Problem for React",
        img: require('../Image/pexels-yan-krukov-7792843.jpg'),
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud ex consequat.',
        longDesc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque sit amet. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud ex porttitor eget dolor. Tellus mauris a diam maecenas sed enim ut sem viverra. Eget nullam non nisi est sit. Tincidunt dui ut ornare lectus. Diam donec adipiscing tristique risus nec. Sapien faucibus et molestie ac feugiat sed. Sit amet mattis vulputate enim nulla aliquet porttitor lacus luctus. Magna etiam tempor orci eu lobortis. Sem et tortor consequat id porta nibh venenatis cras. Interdum varius sit amet mattis vulputate enim nulla. Nec nam aliquam sem et tortor. Arcu dictum varius duis at consectetur lorem. Feugiat in fermentum posuere urna nec tincidunt. Pellentesque diam volutpat commodo sed egestas egestas fringilla. Amet mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Vel orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Orci nulla pellentesque dignissim enim sit amet venenatis.'

    },
    {
        id: 2,
        title: "How not love React?)",
        img: require('../Image/pexels-realtoughcandycom-11035471.jpg'),
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud ex consequat.',
        longDesc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque sit amet. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud ex porttitor eget dolor. Tellus mauris a diam maecenas sed enim ut sem viverra. Eget nullam non nisi est sit. Tincidunt dui ut ornare lectus. Diam donec adipiscing tristique risus nec. Sapien faucibus et molestie ac feugiat sed. Sit amet mattis vulputate enim nulla aliquet porttitor lacus luctus. Magna etiam tempor orci eu lobortis. Sem et tortor consequat id porta nibh venenatis cras. Interdum varius sit amet mattis vulputate enim nulla. Nec nam aliquam sem et tortor. Arcu dictum varius duis at consectetur lorem. Feugiat in fermentum posuere urna nec tincidunt. Pellentesque diam volutpat commodo sed egestas egestas fringilla. Amet mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Vel orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Orci nulla pellentesque dignissim enim sit amet venenatis.'

    },
    {
        id: 3,
        title: "Cool paractics in coding",
        img: require('../Image/pexels-antonio-batinić-4164418.jpg'),
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud ex consequat.',
        longDesc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque sit amet. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud ex porttitor eget dolor. Tellus mauris a diam maecenas sed enim ut sem viverra. Eget nullam non nisi est sit. Tincidunt dui ut ornare lectus. Diam donec adipiscing tristique risus nec. Sapien faucibus et molestie ac feugiat sed. Sit amet mattis vulputate enim nulla aliquet porttitor lacus luctus. Magna etiam tempor orci eu lobortis. Sem et tortor consequat id porta nibh venenatis cras. Interdum varius sit amet mattis vulputate enim nulla. Nec nam aliquam sem et tortor. Arcu dictum varius duis at consectetur lorem. Feugiat in fermentum posuere urna nec tincidunt. Pellentesque diam volutpat commodo sed egestas egestas fringilla. Amet mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Vel orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Orci nulla pellentesque dignissim enim sit amet venenatis.'

    },
]